name: Build and Release Kotlin CLI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to release from"
        required: true
        type: string

jobs:
  build:
    env:
      SPHA_VERSION: ${{ inputs.tag || github.ref_name }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ env.SPHA_VERSION }}
      - name: Set up JDK 24
        uses: actions/setup-java@v5
        with:
          java-version: '24'
          distribution: 'corretto'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d156388eb19639ec20ade50009f3d199ce1e2808

      - name: Package distribution
        run: ./gradlew installDist


      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.SPHA_VERSION }}
          files: build/install/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
